### ISSUE TITLE
Fix webhook auth failures

### ISSUE THREAD

**Issue by ChrisAnstey** [crowdproperty/modulr-hmac-php-client#4]
We were getting quite a few callbacks rejected, due to auth.

The code on live had some commented out code, to set the date for auth check from the date supplied with call (which is what we need to use when checking auth). This meant the call would only auth if it got processed on our side at the same second that Modulr made the call (so times were same anyway).

Update code to make sure datetime is set to the value in api call.

**Comment by stewis** [comment]
Hi Chris,

The time should be the one on the server and not the time sent in the request as you need to authenticate the payload using only the cert modulr sent when seting up..  The issue will be either the time is out on the live server,  or as has happened in the past the time is out of sync on Modulr.  Ask kyle as this has happened in the past.

See:

https://modulr.readme.io/docs/authentication

and more importantly:

System time
The HMAC calculation above uses a date/time value and also implements the recommended clock-skew from the HMAC specification to prevent against replay attacks. It is therefore essential that the sending system has an accurate time (e.g. synchronised with NTP), any significant time error may cause the request to be rejected.

All time values are sent in UTC/GMT, so you should ensure this still continues to send the correct UTC/GMT time if your sending system is subject to changes for daylight savings.

hope this helps.

Stewart

**Comment by stewis** [comment]
The commented out code was there as a bodge while we waited for modulr to fix the issue last time.

**Comment by ChrisAnstey** [comment]
Hi Stewart,

Thanks for the info. I have actually logged out the details of examples which failed auth, and they're the ones where our side processes the request at some point in the second just after the one in which they sent the request. Eg, they send a request at exactly `10:00:03.934` (i.e. `10:00:03`, plus `.934` of a second), and the timestamp includes time as `10:00:03`. When it hits our server, the time has reach `10:00:04.027`, i.e. 93 milliseconds later, but if we use `10:00:04` when calculating the hash, it'll completely mismatch from the hash they calculated, using `10:00:03`.

Using the timestamp supplied in the request works, as expected.

I should have added in here about _also_ checking that the supplied timestamp is within a certain timeperiod of the current server time - hence retaining the temporal security against replay attacks.

Chris

**Comment by stewis** [comment]
Hi Chris,

You should not rely on the time sent in their request as this will allow people to replay requests sent to a webhook.  As this is a financial you obviously do not want that.  As per the modulr spec:

https://modulr.readme.io/docs/notifications-1

Webhook security
We sign the POST request with an HMAC digest, using a secret that you provide. This can be set when registering the endpoint for the webhook type of notification. It is required that you validate this signature, particularly if you are acting upon these events to authorise actions in your system. The method of calculation of the hmac signature is the same as in HMAC Signatures / Authorisation header calculation
For webhook requests that are sent from us to you, we use the webhook id as the key and the secret you have provided when creating the webhook to sign the webhook.

To solve this issue correctly you need to work out who's time is out of sync.  I am not sure what time keeping service you use but you can start by checking timedatectl to see if its syncronised.  

https://linuxconfig.org/how-to-sync-time-on-ubuntu-18-04-bionic-beaver-linux

I can't remember what timekeeping service you would be using though.

I do remember that Modulr used different systems for inbound (API) requests and outbound (webhook) requests.  As I suspect you are not having issues with inbound requests from modulr I suspect their time is out on their server that sends requests to yours.  This happened in the past and I would suggest you speak to Kyle about what we did previously.  It's important that you validate the request using the system time.  As you are validating their inbound requests using your system time I would suggest its an issue their end.

Stewart

**Comment by stewis** [comment]
Although as a side note.  I don't think you do anything with the webhooks data but get a fresh copy of whatever changed from Modulr meaning that validating the request is a minor point although other people may be using this code in their application.

If you are not validating the request correctly and just need to get this to work you can whitelist the ip addresses supplied from modulr and just ignore the authorisation which I suspect other modulr clients are doing.

Good luck! 
Stewart

**Comment by ChrisAnstey** [comment]
It doesn't seem like the system times are out, as 95% of requests were working fine when using our system time. It only was a few percent erroring (and even then, one of the retires would most likely work fine).

The erroring ones were all where the system time on our side was one second after the time specified in their request.

Verifying the HMAC will only work if we use the time that they used, so we may as well use the time that they say they used. As mentioned above, I will also make sure that the time of the request is within a specific timeperiod of the current time - I believe 300ms is default. Hence we'll still keep the protection against replay attacks.

**Comment by stewis** [comment]
Hi Chris,

Maybe you are right its just we never had any rejected inbound that i noticed.  Maybe the real solution is to generate the hash based on -1 second and + 1 second and check if one of the 3 validates.  Then you can assume the request is valid?

Stewart

**Comment by stewis** [comment]
by one of 3 i mean 

a hash based on -1 second
a hash based on the current time
and a hash based on +1 second

**Comment by stewis** [comment]
I assume that is what modulr is doing when they say "any significant time error may cause the request to be rejected."

**Comment by ChrisAnstey** [comment]
Fix added to [0.4.1](https://github.com/crowdproperty/modulr-hmac-php-client/tree/0.4.1).
